### ISSUE TITLE
[TODO] DSS System Stabilizer Module Translation

### ISSUE THREAD

**Issue by zachhuang610** [MakerAcademy/py-maker#1]
### Goal: Translate DSS System Stabilizer Module
**Submodules**
- [x] [Flapper](https://docs.makerdao.com/smart-contract-modules/system-stabilizer-module/flap-detailed-documentation)
- [ ] [Flopper](https://docs.makerdao.com/smart-contract-modules/system-stabilizer-module/flop-detailed-documentation)
- [ ] [Vow](https://docs.makerdao.com/smart-contract-modules/system-stabilizer-module/vow-detailed-documentation)

**Comment by zachhuang610** [comment]
drafted Flapper module translation under daiAuction.py
