### ISSUE TITLE
[TODO] DSS Liquidation 2.0 Module Translation

### ISSUE THREAD

**Issue by zachhuang610** [MakerAcademy/py-maker#2]
## Goal: Translate Liquidation 2.0 Module
**Submodules**
- [ ] [Dog](https://docs.makerdao.com/smart-contract-modules/dog-and-clipper-detailed-documentation#vault-liquidation)
- [ ] [Clip](https://docs.makerdao.com/smart-contract-modules/dog-and-clipper-detailed-documentation#auction-initiation)
- [ ] [Abacus](https://etherscan.io/address/0x7d9f92DAa9254Bbd1f479DBE5058f74C2381A898#code)
